### ISSUE TITLE
Cannot install on Windows

### ISSUE THREAD

**Issue by lfnothias** [mandelbrot-project/memo_publication_examples#1]
I am getting the following when following the installation instructions on Win 64.
```

PackagesNotFoundError: The following packages are not available from current channels:

  - scikit-bio
```

Which is likely due to the lack of support for win-64 packages on conda-forge: https://github.com/biocore/scikit-bio/issues/1711

**Comment by ArnaudGaudry** [comment]
Thanks for the issue! We saw that error with scikit-bio, you can try to install install before installing memo, it should solve it.
``` console
pip install scikit-bio
pip install memo-ms
```
I changed the package order in the environment file, so it should fix it.
